# caminho padr�o paratodo contexto do projeto
server.servlet.context-path=/clinica-voll

# nunca devolve o trace do retorno de erro da aplicacao
server.error.include-stacktrace=never

spring.datasource.url=${DATASOURSE_URL}
spring.datasource.username=${DATASOURSE_USERNAME}
spring.datasource.password=${DATASOURSE_PASSWORD}
spring.datasource.driver-class-name=${DATASOURSE_DRIVE}

# jpa
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false